name: 'Action Lambda Build with Plugins'
description: 'Build of lambda with Actions w/ support to ESBUILD plugins'
inputs:
  base_dir:
    description: 'Source directory'
    default: 'src'
  builder:
    description: 'Builder'
    default: 'esbuild'
  bundle:
    description: 'Activate bundle'
    default: 'true'
  functions:
    description: 'A .yml file where functions is configured'
    default: 'serverless.yml'
  external:
    description: 'External libs'
    default: '["aws-sdk"]'
  individually:
    description: 'Build individually functions'
    default: 'true'
  minify:
    description: 'Activate minify'
    default: 'true'
  outdir:
    description: 'Output directory'
    default: 'build'
  sourcemap:
    description: 'Activate sourcemap'
    default: 'true'
  three_shaking:
    description: 'Activate three_shaking'
    default: 'true'
  zip:
    description: 'Zip functions'
    default: 'true'
  loader:
    # loader: '{".mustache": "copy"}'
    description: 'Add esbuild loaders, ex: {".mustache": "copy"}'
    default: '{}'
  extensions:
    description: 'Add more filter files extensions, separate by comma, js* and ts* is already added, dont need add again  ex: "mjs,cjs,png"'
    default: ''
  static_path:
    description: 'Copy path to build'
  plugins:
    description: 'Add esbuild plugins'
    default: '[]'

runs:
  using: 'docker'
  image: 'Dockerfile'
